### ISSUE TITLE
Clay World Gen Crash

### ISSUE THREAD

**Issue by WenXin20** [The-Fireplace-Minecraft-Mods/Fires-Clay-Spawn#1]
Fire's Clay Spawn v7.1.2
Forge v14.23.5.2821
Minecraft v1.12.2

I randomly get this crash while in the world, downgrading to version 7.1.1 works fine for me.
[Crash Report](https://gist.github.com/WenXin20/5fd2da898acdd056f0f3bc61acd0d6e1)

**Comment by The-Fireplace** [comment]
Your crash report leads to a 404, but yeah, I've seen it too. If you could post your crash report again, that would be helpful, and I'll look in to it when I get the chance

**Comment by WenXin20** [comment]
Thanks! Here's the [report](https://gist.github.com/WenXin20/5fd2da898acdd056f0f3bc61acd0d6e1) again. The link above should also be fixed now.
